server:
  port: 7002
eureka:
  instance:
      # eureka服务端的实例名称
    hostname: eureka7002.com
  client:
        # 不注册自己
    register-with-eureka: false
        # 表示自己是注册中心，不用检索服务
    fetch-registry: false
    service-url:
      #相互注册
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    #自我保护机制，默认为开启true
    enable-self-preservation: true
    #心跳检测间隔：2000ms
    eviction-interval-timer-in-ms: 2000