spring:
  application:
    name: cloud-consemer-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    password: 123456
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.lc.springcloud.dto
server:
  port: 80
  servlet:
    context-path: /web
eureka:
  client:
    # 是否注册自己
    register-with-eureka: false
    # 表示自己是注册中心，不用检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
ribbon:
  # 建立连接后，在服务端读取数据的时间
  ReadTimeout: 5000
  # 建立连接所需的时间
  ConnetTimeout: 5000
logging:
  level:
    # feign 日志以什么级别监控哪个接口
    com.lc.spriongcloud.service.OrderService: debug