server:
  port: 9501
spring:
  application:
    name: cloud-gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    password: 123456
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh           # 路由的 ID，没有固定规则但要求唯一
#          uri: http://localhost:8001  # 匹配后蹄冻服务的路由地址
#          predicates:
#            - Path=/web/payment/hystrix/ok/**   # 断言，路径相匹配的进行路由
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
          predicates:
             - Path=/web/payment/get/**         #断言，路径相匹配的进行路由
#             - Host=**.springcloud.com          #curl命令：-H "HOST:www.springcloud.com"  Host名称必须带有.springcloud.com
#             - Cookie=username,gujx            #curl命令：--cookie "username=gujx"   必须带有Cookie:username=gujx
#             - Method=POST                     #请求方式必须为Post
#             - After=2020-12-17T21:30:07.380+08:00[Asia/Shanghai] #在指定时间之后的服务可以被访问
#             - Query=username,admin              #请求参数必须带有username=admin(admin可以写作正则表达式)
#             - Header=cloud,\d+                 #请求头必须带有cloud参数并且value必须为数字
#             - Before=2020-12-17T21:30:07.380+08:00[Asia/Shanghai] #在指定时间之前的服务可以被访问
#          filter:
#            - AddRequestHeader=X-Request-red,blue #过滤器

        - id: payment_routh2           # 路由的 ID，没有固定规则但要求唯一
#          uri: http://localhost:8001  # 匹配后蹄冻服务的路由地址
#          predicates:
#            - Path=/web/payment/hystrix/timeout/**    # 断言，路径相匹配的进行路由
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
          predicates:
              - Path=/web/payment/hystrix/timeout/**         #断言，路径相匹配的进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka